phrase = "Giraffe Academy"
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase[3])
print(phrase.index("G"))
print(phrase.index("Academy"))
# print(phrase.index("z")) : This code shows error because there is no "z" in phrase
print(phrase.replace("Giraffe", "Elephant"))
print(phrase + " is Cool")
print("Giraffe Academy")
print("Giraffe\nAcademy")
print("Giraffe\"Academy")
